//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitroCast.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NitroCast.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {2} - {3}.
        /// </summary>
        internal static string ProgressBarExportClass {
            get {
                return ResourceManager.GetString("ProgressBarExportClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete..
        /// </summary>
        internal static string ProgressBarExportComplete {
            get {
                return ResourceManager.GetString("ProgressBarExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string ProgressBarExportText {
            get {
                return ResourceManager.GetString("ProgressBarExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associating Internal Data Types.
        /// </summary>
        internal static string ProgressBarLoadAssociate {
            get {
                return ResourceManager.GetString("ProgressBarLoadAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Internal Data Types.
        /// </summary>
        internal static string ProgressBarLoadBuild {
            get {
                return ResourceManager.GetString("ProgressBarLoadBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed..
        /// </summary>
        internal static string ProgressBarLoadFailed {
            get {
                return ResourceManager.GetString("ProgressBarLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0}....
        /// </summary>
        internal static string ProgressBarLoadInitialize {
            get {
                return ResourceManager.GetString("ProgressBarLoadInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing {0}....
        /// </summary>
        internal static string ProgressBarLoadParse {
            get {
                return ResourceManager.GetString("ProgressBarLoadParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Referenced Data Types.
        /// </summary>
        internal static string ProgressBarLoadReferences {
            get {
                return ResourceManager.GetString("ProgressBarLoadReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Internal Data Types.
        /// </summary>
        internal static string ProgressBarLoadSort {
            get {
                return ResourceManager.GetString("ProgressBarLoadSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        internal static string ProgressBarLoadText {
            get {
                return ResourceManager.GetString("ProgressBarLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        internal static string ProgressBarSaveFailed {
            get {
                return ResourceManager.GetString("ProgressBarSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving folder {0}....
        /// </summary>
        internal static string ProgressBarSaveFolders {
            get {
                return ResourceManager.GetString("ProgressBarSaveFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving references....
        /// </summary>
        internal static string ProgressBarSaveReferences {
            get {
                return ResourceManager.GetString("ProgressBarSaveReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0}....
        /// </summary>
        internal static string ProgressBarSaveText {
            get {
                return ResourceManager.GetString("ProgressBarSaveText", resourceCulture);
            }
        }
    }
}
