//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitroCast.Core.Support {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReservedKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReservedKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NitroCast.Core.Support.ReservedKeywords", typeof(ReservedKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSOLUTE,ACTION,ADD,ADMINDB,ALL,ALLOCATE,ALPHANUMERIC,ALTER,AND,ANY,ARE,AS,ASC,ASSERTION,AT,AUTHORIZATION,AUTOINCREMENT,AVG,BAND,BEGIN,BETWEEN,BINARY,BIT,BIT_LENGTH,BNOT,BOR,BOTH,BXOR,BY,BYTE,CASCADE,CASCADED,CASE,CAST,CATALOG,CHAR,CHARACTER,CHAR_LENGTH,CHARACTER_LENGTH,CHECK,CLOSE,COALESCE,COLLATE,COLLATION,COLUMN,COMMIT,COMP,COMPRESSION,CONNECT,CONNECTION,CONSTRAINT,CONSTRAINTS,CONTAINER,CONTINUE,CONVERT,CORRESPONDING,COUNT,COUNTER,CREATE,CREATEDB,CROSS,CURRENCY,CURRENT,CURRENT_DATE,CURRENT_TIME,CURRENT_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keywords_JetSQL {
            get {
                return ResourceManager.GetString("Keywords_JetSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSOLUTE,ACTION,ADA,ADD,ALL,ALLOCATE,ALTER,AND,ANY,ARE,AS,ASC,ASSERTION,AT,AUTHORIZATION,AVG,BEGIN,BETWEEN,BIT,BIT_LENGTH,BOTH,BY,CASCADE,CASCADED,CASE,CAST,CATALOG,CHAR,CHAR_LENGTH,CHARACTER,CHARACTER_LENGTH,CHECK,CLOSE,COALESCE,COLLATE,COLLATION,COLUMN,COMMIT,CONNECT,CONNECTION,CONSTRAINT,CONSTRAINTS,CONTINUE,CONVERT,CORRESPONDING,COUNT,CREATE,CROSS,CURRENT,CURRENT_DATE,CURRENT_TIME,CURRENT_TIMESTAMP,CURRENT_USER,CURSOR,DATE,DAY,DEALLOCATE,DEC,DECIMAL,DECLARE,DEFAULT,DEFERRABLE,DEFERRED,DELETE,DESC,DESCRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keywords_ODBC {
            get {
                return ResourceManager.GetString("Keywords_ODBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Keywords_PostgreSQL {
            get {
                return ResourceManager.GetString("Keywords_PostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABSOLUTE,ACTION,ADMIN,AFTER,AGGREGATE,ALIAS,ALLOCATE,ARE,ARRAY,ASSERTION,AT,BEFORE,BINARY,BIT,BLOB,BOOLEAN,BOTH,BREADTH,CALL,CASCADED,CAST,CATALOG,CHAR,CHARACTER,CLASS,CLOB,COLLATION,COMPLETION,CONNECT,CONNECTION,CONSTRAINTS,CONSTRUCTOR,CORRESPONDING,CUBE,CURRENT_PATH,CURRENT_ROLE,CYCLE,DATA,DATE,DAY,DEC,DECIMAL,DEFERRABLE,DEFERRED,DEPTH,DEREF,DESCRIBE,DESCRIPTOR,DETERMINISTIC,DICTIONARY,DIAGNOSTICS,DISCONNECT,DOMAIN,DYNAMIC,EACH,END-EXEC,EQUALS,EVERY,EXCEPTION,EXTERNAL,FALSE,FIRST,FLOAT,FOUND,FREE,GENERAL, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keywords_SQLFuture {
            get {
                return ResourceManager.GetString("Keywords_SQLFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD,ALL,ALTER,AND,ANY,AS,ASC,AUTHORIZATION,BACKUP,BEGIN,BETWEEN,BREAK,BROWSE,BULK,BY,CASCADE,CHECK,CHECKPOINT,CLOSE,CLUSTERED,COALESCE,COLLATE,COLUMN,COMMIT,COMPUTE,CONSTRAINT,CONTAINS,CONTAINSTABLE,CONTINUE,CONVERT,CREATE,CROSS,CURRENT,CURRENT_DATE,CURRENT_TIME,CURRENT_TIMESTAMP,CURRENT_USER,CURSOR,DATABASE,DBCC,DEALLOCATE,DECLARE,DEFAULT,DELETE,DENY,DESC,DISK,DISTINCT,DISTRIBUTED,DOUBLE,DROP,DUMMY,DUMP,ELSE,END,ERRLVL,ESCAPE,EXCEPT,EXEC,EXECUTE,EXISTS,EXIT,FETCH,FILE,FILLFACTOR,FOR,FOREIGN,FREETEXT,FREETE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keywords_SQLServer {
            get {
                return ResourceManager.GetString("Keywords_SQLServer", resourceCulture);
            }
        }
    }
}
